get  'tips_chips',         :to => 'tips_chips#index'
get  'tips_chips/new',     :to => 'tips_chips#new'
post 'tips_chips/new',     :to => 'tips_chips#new'
get  'tips_chips/edit',    :to => 'tips_chips#edit'
post 'tips_chips/edit',    :to => 'tips_chips#edit'
post 'tips_chips/destroy', :to => 'tips_chips#destroy'
